# Generated by Django 2.2.5 on 2019-11-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='pics')),
                ('offers', models.BooleanField()),
                ('head', models.CharField(max_length=133)),
                ('descrption', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
