# Generated by Django 2.2.5 on 2019-11-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='pics')),
                ('date', models.DateField()),
                ('head', models.CharField(max_length=133)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
